pg_pathman.c
Hello,
During testing, I found a corner case issue. If the first query executed on the cluster after a restart is a DROP TABLE of a partitionned table, it'll fail because the configuration will be loaded after the effective drop, but with the pathman_config table not up to date.
This commit moves the load_config() call to post_parse_analyze hook, which is also called for utility statement. If the overhead of calling a hook for every query just for this purpose is too much, ProcessUtility hook could be used instead, but the load_config() call would be duplicated. Let me know what you prefer.
Regards
=> Load configuration in post_parse_analyze hook

range.sql
The check is always false as v_child_relname is schema-qualified while the
comparison is to a plain table name.  The entire check can be removed
instead of fixing it as a few lines above we have a loop which comes up with
a unique name.
=> range.sql: drop redundant check for existing tables

.editorconfig
For some reason github formats tabs as eight spaces, this messes up the formatting of sql files in pg_pathman.  For example compare:
https://github.com/postgrespro/pg_pathman/blob/master/range.sql
to:
https://github.com/michelp/pg_pathman/blob/master/range.sql
this PR drops an editorconfig file to improve formatting.
=> dot editorconfig

README.md
Recently it took me quite a while to investigate why dropped partitioned tables were not removed from `pathman_config` when `DROP TABLE ` was executed on replica side inside trigger on logically replicated table, so I thought it might be useful to add this to the docs.
=> Advice to configure pathman_ddl_trigger ENABLE ALWAYS on LR replica

Makefile
When included into postgresql contribs, and postgresql configured "out of source", pg_pathman could not build because it misses include path.
Fix it by referring top_srcdir and subdir if build without USE_PGXS.
=> Fix out of source build

src/include/partition_filter.h, src/partition_filter.c, src/utility_stmt_hooking.c
Main points:
* COPY FROM to foreign partitions is performed only if it is needed and possible, nothing should be changed for existing users.
* Some callback args were simplified.
* Small bug fixed: previously we could specify `COPY FROM ... FREEZE FALSE` and copy would fail.
=> Foreign copy from for pg_shardman

expected/pathman_expressions_1.out, expected/pathman_permissions.out, expected/pathman_rebuild_deletes.out, expected/pathman_rebuild_deletes_1.out, expected/pathman_rebuild_updates_1.out, sql/pathman_expressions.sql, sql/pathman_permissions.sql, sql/pathman_rebuild_updates.sql, src/compat/pg_compat.c, src/hooks.c, src/include/compat/pg_compat.h, src/include/hooks.h, src/include/partition_filter.h, src/include/relation_info.h, src/init.c, src/nodes_common.c, src/partition_filter.c, src/partition_router.c, src/pathman_workers.c, src/pg_pathman.c, src/pl_funcs.c, src/pl_range_funcs.c, src/planner_tree_modification.c, src/relation_info.c, src/utility_stmt_hooking.c, tests/python/Makefile, tests/python/partitioning_test.py
I kinda lost interest to exorcise a couple of tests further in attempts to make
them pass on all supported versions and just added copies. These are
* pathman_expressions now differs because planner converts ROW(Const, Const) to
just Const of record type.
* Same with pathman_rebuild_updates.
I have removed inclusion of partition_filter.h in pg_compat.h in 9.5 as it
created circular dependency hell. I think it is not worthwhile to fight with it
since the only thing actually needed was error message, which is used in this
single place.
Small typo fix in partitioning_test.py: con2.begin instead of con1.begin.
Finally, run python tests with --failfast and --verbose options.
=> Adapt pg_pathman for PG 11.

Makefile, README.md, expected/pathman_CVE-2020-14350.out, hash.sql, init.sql, range.sql, sql/pathman_CVE-2020-14350.sql, src/partition_creation.c, src/pathman_workers.c
Fix for CVE-2020-14350 (https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-14350)
See also Postgres commit 7eeb1d986.
Thanks to Alexander Lakhin.
=> CVE-2020-14350

expected/pathman_CVE-2020-14350.out, expected/pathman_calamity_3.out, expected/pathman_cte_2.out, expected/pathman_join_clause_2.out, expected/pathman_subpartitions.out, expected/pathman_subpartitions_1.out, expected/pathman_views_3.out, patches/REL_14_STABLE-pg_pathman-core.diff, sql/pathman_CVE-2020-14350.sql, sql/pathman_subpartitions.sql, src/compat/pg_compat.c, src/hooks.c, src/include/compat/pg_compat.h, src/include/hooks.h, src/include/partition_router.h, src/nodes_common.c, src/partition_creation.c, src/partition_filter.c, src/partition_overseer.c, src/partition_router.c, src/planner_tree_modification.c, src/relation_info.c, src/utility_stmt_hooking.c
Porting to v14 has difficulties because the internal API has changed seriously.
So this porting requires some changes in the source PostgreSQL codes and can
not be applied to vanilla without patch.
=> Postgresql 14 port

expected/pathman_rebuild_updates.out, expected/pathman_rebuild_updates_1.out, sql/pathman_rebuild_updates.sql, src/include/partition_filter.h, src/partition_filter.c
Added 'tuple map' for prevent addition extra columns values into partitions
=> PGPRO-5113 Added 'tuple map' for prevent addition extra columns values into partitions

src/pg_pathman.c
Added callback for reset pg_pathman cache at start and at finish ATX transaction
=> [PGPRO-5614] Reset cache at start and at finish ATX transaction

src/pg_pathman.c
Reset cache at start and at finish ATX transaction (for v10-v12)
=> Reset cache at start and at finish ATX transaction (for v10-v12)

src/pathman_workers.c
Sometimes pg_patman is freezes for 1 min (in case it started unde Valgrind and complied with -Og option).
This change (for variable failures_count) fixes it.
=> [PGPRO-5360] Fix for freeze (Valgrind and compilation with -Og option)

src/compat/rowmarks_fix.c, src/include/compat/rowmarks_fix.h
PGPRO-6148, PGPRO-7080: Use common macro for all PG versions instead of add_vars_to_targetlist() function.
Reason: b3ff6c74
=> PGPRO-6148, PGPRO-7080: Use common macro for all PG versions instead of add_vars_to_targetlist() function

src/pl_funcs.c, src/pl_hash_funcs.c, src/pl_range_funcs.c
Due to the commit c8b2ef05f481ef06326d7b9f3eb14b303f215c7e in PostgreSQL 16:
- The macro CStringGetTextDatum returns a Datum, so use the more appropriate macro PG_RETURN_DATUM instead of PG_RETURN_TEXT_P.
- The input to the macro TextDatumGetCString must be of type Datum, so use the more appropriate macro PG_GETARG_DATUM instead of PG_GETARG_TEXT_P.
=> Fix build due to new checks in PostgreSQL 16

src/partition_creation.c, src/relation_info.c, src/runtime_merge_append.c
See the commit 0fe954c28584169938e5c0738cfaa9930ce77577 (Add -Wshadow=compatible-local to the standard compilation flags) in PostgreSQL 16.
```
src/relation_info.c: In function ‘resowner_prel_add’:
src/relation_info.c:74:31: warning: declaration of ‘old_mcxt’ shadows a previous local [-Wshadow=compatible-local]
74 |                 MemoryContext old_mcxt = MemoryContextSwitchTo((prel)->mcxt); \
|                               ^~~~~~~~
src/relation_info.c:608:17: note: in expansion of macro ‘LeakTrackerAdd’
608 |                 LeakTrackerAdd(prel);
|                 ^~~~~~~~~~~~~~
src/relation_info.c:592:41: note: shadowed declaration is here
592 |                 MemoryContext           old_mcxt;
|                                         ^~~~~~~~
src/relation_info.c: In function …
```
=> Fix compiler warnings due to new checks in PostgreSQL 16

expected/pathman_join_clause_4.out, expected/pathman_lateral_4.out, expected/pathman_only_3.out, expected/pathman_runtime_nodes_1.out, src/compat/pg_compat.c, src/init.c, src/nodes_common.c, src/partition_creation.c, src/partition_router.c, src/pg_pathman.c, src/relation_info.c
The commit d3536253d948ba0289e7ad82ae256d8c2b9cd12a was added to fix regression.diffs after running the tests:
```
diff -U3 /home/marina/pg_pathman/expected/pathman_join_clause_2.out /home/marina/pg_pathman/results/pathman_join_clause.out
--- /home/marina/pg_pathman/expected/pathman_join_clause_2.out	2022-11-21 14:11:54.399449877 +0300
+++ /home/marina/pg_pathman/results/pathman_join_clause.out	2022-12-14 09:14:34.999078710 +0300
@@ -44,23 +44,23 @@
Nested Loop
->  Seq Scan on fk
->  Custom Scan (RuntimeAppend)
-         Prune by: (fk.id1 = m.id1)
+         Prune by: (m.id1 = fk.id1)
->  Seq Scan on mytbl_0 m
-               Filter: ((fk.id1 = id1) AND (fk.id2 = id2) AND (NOT (key <@ int4range(6, fk.end_key))))
+               Filter: ((id1 = fk.id1) AND (fk.id2 = id2) AND (NOT (key <@ …
```
=> Fixes related to new changes in PostgreSQL 16: October 25, 2022 - November 15, 2022

src/include/init.h, src/init.c, src/pl_funcs.c
Added 'volatile' modifier for local variables that are modified in PG_TRY and read in PG_CATCH/PG_FINALLY
=> [PGPRO-7417] Added 'volatile' modifier for local variables

expected/pathman_permissions_1.out, src/include/compat/pg_compat.h, src/include/partition_filter.h, src/partition_filter.c, src/pg_pathman.c, src/pl_funcs.c, src/planner_tree_modification.c, src/utility_stmt_hooking.c, src/utils.c
* Convert the reg* input functions to report (most) errors softly.
See the commit 858e776c84f48841e7e16fba7b690b76e54f3675 (Convert the reg* input functions to report (most) errors softly.) in PostgreSQL 16.
The function qualified_relnames_to_rangevars is used in the functions create_hash_partitions_internal and create_range_partitions_internal. It looks like these functions should not skip partition names (e.g. in the functions create_hash_partitions and create_range_partitions respectively)..
* Add grantable MAINTAIN privilege and pg_maintain role.
See the commit 60684dd834a222fefedd49b19d1f0a6189c1632e (Add grantable MAINTAIN privilege and pg_maintain role.) in PostgreSQL 16.
Since pathman_permissions_1.out is already in use for PostgreSQL 16+ (see the commit …
=> Fixes related to new changes in PostgreSQL 16: December 6, 2022 - December 27, 2022

expected/pathman_cache_pranks_1.out, expected/pathman_calamity.out, expected/pathman_calamity_1.out, expected/pathman_calamity_2.out, expected/pathman_calamity_3.out, sql/pathman_cache_pranks.sql, src/include/utils.h, src/nodes_common.c, src/pathman_workers.c, src/pl_funcs.c, src/pl_range_funcs.c, src/utils.c
1) [PGPRO-7880] Need to check relation Oid before locking
2) [PGPRO-7870] Added error for case executing prepared query after DROP/CREATE EXTENSION
=> PGPRO 7870

expected/pathman_runtime_nodes.out, expected/pathman_runtime_nodes_1.out, sql/pathman_runtime_nodes.sql, src/hooks.c, src/include/hooks.h, src/init.c
[PGPRO-7928] Variable pg_pathman.enable must be called before any query
=> [PGPRO-7928] Variable pg_pathman.enable must be called before any query

src/include/compat/pg_compat.h, src/utility_stmt_hooking.c
Correct number of args in ExecInitRangeTable(), ExecInsertIndexTuples(), ExecBRUpdateTriggers() and ExecBRDeleteTriggers().
Caused by:
- b803b7d132e3505ab77c29acf91f3d1caa298f95 Fill EState.es_rteperminfos more systematically.
- 19d8e2308bc51ec4ab993ce90077342c915dd116 Ignore BRIN indexes when checking for HOT updates
- 9321c79c86e6a6a4eac22e2235a21a8b68388723 Fix concurrent update issues with MERGE. Tags: pg_pathman
=> PGPRO-8238, PGPRO-8122: Fix build with master at 5df319f3d. Corrected number of args in some functions.
